config/routes.rb
Rails.application.routes.draw do
  resources :responses, only: [:index, :new, :create]
  root to: 'responses#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  def self.default_question
    find_or_create_by(prompt: 'Are you happy today?')
  end
end

app/models/response.rb
class Response < ApplicationRecord
  ANSWER_MAPPING = {
    0 => 'sad',
    2 => 'normal',
    3 => 'happy'
  }
  VALUE_MAPPING = ANSWER_MAPPING.invert

  belongs_to :question
  validates :answer, :question, presence: true

  def answer_in_text
    ANSWER_MAPPING[answer]
  end

  def created_date
    created_at.to_date
  end

  def self.answer_on(date)
    duration = date.beginning_of_day..date.end_of_day
    where(created_at: duration)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  # GET /responses
  def index
    @responses = Response.all.order(created_at: :asc)

    respond_to do |format|
      format.html {
        @average = Response.average(:answer).round(2)

        @style = if @average > 2
          'happy'
        elsif @average > 1
          'normal'
        else
          'sad'
        end
      }

      format.json {
        data = @responses.map do |response|
          {
            created_date: response.created_date,
            answer: response.answer
          }
        end
        render json: data
      }
    end
  end

  # GET /responses/new
  def new
    if Response.answer_on(Date.today).exists?
      render 'already_answer'
    else
      @question = Question.default_question
      @response = Response.new
    end
  end

  # POST /responses
  def create
    response_params = params.permit(:answer, :detail)
    question = Question.default_question
    response = Response.new(response_params.merge(question_id: question.id))

    if response.save
      render json: { status: 'success' }, status: 200
    else
      render json: { error: response.errors.full_messages.join(', ') }, status: 422
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happiness Trend</title>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/responses/already_answer.html.erb
<%= stylesheet_link_tag 'responses_already_answer' %>

<h1 class='rated'>
  <div>You already rated today</div>
  <div>Left tomorrow rating for tomorrow you</div>
  <div>^_^</div>
</h1>

<div class='past_rating'>
  <%= link_to'For now, you can view your past rating here', responses_path %>
</div>

app/views/responses/index.html.erb
<%= stylesheet_link_tag 'responses_index' %>

<div class='title'>
  <h1>
    Your average happiness score:
  </h1>

  <div class='average'>
    <span class="box <%= @style %>">
      <%= @average %>
    </span>
  </div>
</div>

<div class='trend'></div>

<div class='responses'>
  <% @responses.each do |response| %>
    <div><%= response.created_at.strftime('%F') %>
    <div class="row <%= response.answer_in_text %>">
      <div class='detail'><%= simple_format(response.detail) %></div>
    </div>
  <% end %>
</div>

<div class='action'>
  <%= link_to 'New Response', new_response_path %>
</div>

<%= javascript_include_tag 'responses_index' %>

app/views/responses/new.html.erb
<%= stylesheet_link_tag 'responses_new' %>

<h1 class='question'><%= @question.prompt %></h1>

<div class='choices'>
  <span><%= image_tag 'sad_face.png', class: 'choice', data: { value: Response::VALUE_MAPPING['sad'] } %></span>
  <span><%= image_tag 'straight_face.png', class: 'choice', data: { value: Response::VALUE_MAPPING['normal'] } %></span>
  <span><%= image_tag 'happy_face.png', class: 'choice', data: { value: Response::VALUE_MAPPING['happy'] } %></span>
</div>

<div class='detail'>
  <textarea rows=4 cols=50 placeholder='Please provide detail for your rating'></textarea>
</div>

<div class='action'>
  <button id='submit'>Submit</button>
</div>

<%= javascript_include_tag 'responses' %>